# Generated by Django 5.0.3 on 2024-04-24 07:23

import phonenumber_field.modelfields
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", utils.utils.LowercaseEmailField(max_length=255, unique=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=50, null=True, region="UA"
                    ),
                ),
                ("message", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
