# Generated by Django 5.0.3 on 2024-04-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_feature_product_productrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="features",
            field=models.ManyToManyField(blank=True, null=True, to="shop.feature"),
        ),
        migrations.AlterUniqueTogether(
            name="feature",
            unique_together={("name", "value")},
        ),
    ]
