# Generated by Django 5.0.3 on 2024-04-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_features_alter_feature_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="features",
            field=models.ManyToManyField(blank=True, to="shop.feature"),
        ),
    ]
