# Generated by Django 5.0.3 on 2024-04-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
